name: Release
on:
  push:
    #branches:
    #  - main

jobs:
  #release:
  #  name: release
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: "12.x"
  #    - run: npx semantic-release
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy to GCF
        run: |
          gcloud functions deploy example-google-cloud-function \
            --allow-unauthenticated \
            --trigger-http \
            --set-env-vars APP_ID="${{secrets.APP_ID}}",\
                PRIVATE_KEY="${{secrets.PRIVATE_KEY}}",\
                WEBHOOK_SECRET="${{secrets.WEBHOOK_SECRET}}"
